cli.so:
	gcc -fPIC -shared -llwqq -I/home/konglx/project/ITM-ChatOps-Robot/chat_adapter/qq/lwqq/build -I/home/konglx/project/ITM-ChatOps-Robot/chat_adapter/qq/lwqq/lib cli.c -o cli.so
.PHONY: cli.so

