# 机器人名字，将作为命令前缀
name: Tom
# 机器人home目录
home: /home/konglx/project/TomBot
# 日志级别，有效的取值：debug info warn error critical
log_level: debug
command_prefix: '`'
# 暂时没用
adapter: qq
# 用tcp连接或IPC，默认IPC，adapter和服务端没有部署在一起时有用，现在没用
use_tcp: True
pullpush_socket: tcp://*:4444
subpub_socket: tcp://*:4445
tcp_addr: 
    - publish: 127.0.0.1
    - publish_port: 4447
    - forward: 127.0.0.1
    - forward_port: 4448
    - push: 127.0.0.1
    - push_port: 4449

# IPC文件的目录
ipc_path: /home/konglx/project/TomBot/run
# 此处为true，那么日志级别也被自动设置为debug
debug: True

# 暂时不用
redis_server : 127.0.0.1
redis_port : 9673

# 启用的插件列表
plugins:
    - calc
    - ping
    - help
    - flow
    - qiubai
    - fun
    - bye
    - simsimi
    - notify

ansibles:
  - simple_runner
