name: Tom
home: /home/konglx/project/TomBot
log_level: debug
adapter: qq
use_tcp: False
tcp_addr: 
    - publish: 127.0.0.1
    - publish_port: 4447
    - forward: 127.0.0.1
    - forward_port: 4448
    - push: 127.0.0.1
    - push_port: 4449

ipc_path: /home/konglx/project/TomBot/run
debug: True

redis_server : 127.0.0.1
redis_port : 9673

plugins:
    - calc
    - ping
    - help
    - flow
    - qiubai
    - fun
    - bye
