version: 0.9
# 机器人名字，将作为命令前缀
name: Tom
# 机器人home目录
home: /home/konglx/project/TomBot
# 日志级别，有效的取值：debug info warn error critical

# 用tcp连接或IPC，默认IPC，adapter和服务端没有部署在一起时有用，现在没用
backend:
    log_level: debug
    use_tcp: True
    server_socket: tcp://*:4445
    #默认模式：cmd normal easy
    default_mode: normal
    # IPC文件的目录
    ipc_path: /home/konglx/project/TomBot/run/ipc
    # 是否调试模式
    debug: True
    workers: 5
    max_message_size: 4096
    hide_restrict_command: True
    bot_alt_prefixes:
      - tom
    bot_alt_separators:
      - ','
      - ':'

broker:
    capture: True

proxy:
    enable: False
    host: 192.168.13.19
    port: 7777

# 暂时不用
redis_server : 127.0.0.1
redis_port : 9673

plugin:
  plugin_dirs:
    - /home/konglx/project/TomBot/tombot/plugins
  backlist:
    - ping

ansible:
  - simple_runner

