name: Tom
home: /home/konglx/project/TomBot
log_level: debug
adapter: qq
use_socket: False
socket: 
    - publish: 127.0.0.1:4441
    - forward: 127.0.0.1:4442
    - push: 127.0.0.1:4445

ipc_path: /home/konglx/project/TomBot/run
debug: True

redis_server : 127.0.0.1
redis_port : 9673

plugins:
    - calc
    - ping
    - help
    - flow
    - qiubai
    - fun
    - bye
