req_socket: tcp://192.168.3.107:4445

use_proxy: True
proxy_host: 117.27.132.20
proxy_port: 20445

log_level: info

smtp_host: mail.ffcs.cn
smtp_port: 110
smtp_account: konglx
smtp_password: Jay19880821

verify: 
    use_http: True,
    http_host: 192.168.3.107
    http_port: 8001
    email: konglx@ffcs.cn

